function J_qdot = compute_Jdot(q0,q1,q2,q3,dq0,dq1,dq2,dq3)
%compute_Jdot
%    J_qdot = compute_Jdot(Q0,Q1,Q2,Q3,DQ0,DQ1,DQ2,DQ3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    31-Jul-2025 21:36:38

t2 = dq0.*q1.*2.0;
t3 = dq1.*q0.*2.0;
t4 = dq0.*q2.*2.0;
t5 = dq2.*q0.*2.0;
t6 = dq0.*q3.*2.0;
t7 = dq1.*q2.*2.0;
t8 = dq2.*q1.*2.0;
t9 = dq3.*q0.*2.0;
t10 = dq1.*q1.*4.0;
t11 = dq1.*q3.*2.0;
t12 = dq3.*q1.*2.0;
t13 = dq2.*q3.*2.0;
t14 = dq3.*q2.*2.0;
t15 = dq2.*q2.*4.0;
t16 = dq3.*q3.*4.0;
t20 = dq0./2.0;
t21 = dq1./2.0;
t22 = dq2./2.0;
t23 = dq3./2.0;
t17 = -t10;
t18 = -t15;
t19 = -t16;
t24 = -t21;
t25 = -t22;
t26 = -t23;
J_qdot = reshape([t18+t19,t6+t7+t8+t9,-t4-t5+t11+t12,0.0,0.0,0.0,0.0,-t6+t7+t8-t9,t17+t19,t2+t3+t13+t14,0.0,0.0,0.0,0.0,t4+t5+t11+t12,-t2-t3+t13+t14,t17+t18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t24,t20,t23,t25,0.0,0.0,0.0,t25,t26,t20,t21,0.0,0.0,0.0,t26,t22,t24,t20],[7,6]);
end
